# Generated by Django 3.0.4 on 2020-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('great', 'great'), ('good', 'good'), ('bad', 'bad')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
