# [START django_app]
runtime: python37

env_variables:
  DHAN_DB_SECRET_ID: db_django_password
  DHAN_DB_SECRET_VERSION: 1
  DHAN_DB_USER: django
  DHAN_DB_HOST: /cloudsql/day-has-a-name:asia-northeast1:day-has-a-name-mysql
  DHAN_DB_NAME: day_has_a_name
  DHAN_KEY_SECRET_ID: django_secret_key
  DHAN_KEY_SECRET_VERSION: 1

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
# [END django_app]
